name: benbox
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pillow
  - streamlit
  - pip:
      - anthropic>=0.45.1
      - httpx>=0.28.1
      - mcp[cli]>=1.2.1
      - -r requirements_streamlit.txt
