name: benbox
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - pillow
  - pip:
    - anthropic>=0.45.1
    - httpx>=0.28.1
    - mcp[cli]>=1.2.1
    - -r requirements.txt
