[server]
fileWatcherType = "auto"
runOnSave = true

[browser]
gatherUsageStats = false

[theme]
primaryColor="#FF4B4B"
backgroundColor="#1e1e1e"
secondaryBackgroundColor="#2b2a28"
textColor="#FFFFFF"
font="sans serif"
