[server]
fileWatcherType = "auto"
runOnSave = true

[browser]
gatherUsageStats = false

[theme]
primaryColor="#eb2d34"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#f6f5f4"
textColor="#2e3334"
font="sans serif"
